name: ej1-workflow
on:
 push:
  branches: [ master ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                node-version: 18
            - name: Install dependencies
              run: npm i
            - name: Run tests
              run: npm test
            - name: Checkout
              uses: actions/checkout@v3
  
            - name: Tests
              uses: cloudposse/github-action-docker-compose-test-run@main
              with:
                file: test/docker-compose.yml
                service: app
                command: test/unit-tests.sh
